name: Publish

on:
  workflow_dispatch:
  push:

jobs:
  publish:

    strategy:
      fail-fast: false
      matrix:
        include:
        - { os: windows-latest, rid: win-x64 }
        - { os: windows-latest, rid: win-arm64 }
        - { os: ubuntu-latest, rid: linux-x64 }
        - { os: ubuntu-latest, rid: linux-arm64 }
        - { os: macos-latest, rid: osx-x64 }
        - { os: macos-latest, rid: osx-arm64 }

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8

    - if: matrix.rid == 'linux-arm64'
      run: sudo sh -e .github/workflows/install-ubuntu-arm64.sh

    - run: dotnet publish --sc -c Release -r ${{ matrix.rid }}

    - if: endsWith(matrix.rid, '-x64')
      run: ./bin/Release/net8/${{ matrix.rid }}/native/Shazam.${{ matrix.rid }} .github/workflows/test.mp3 > test-out

    - if: matrix.rid == 'win-x64'
      run: findstr 11188983 test-out

    - if: matrix.rid == 'linux-x64' || matrix.rid == 'osx-x64'
      run: grep 11188983 test-out

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.rid }}
        path: ./bin/Release/*/*/native/*
        retention-days: 1
